AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'
