version: '3'

volumes:
  db-data:
  public-data:

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - '.:/myapp'
      - 'public-data:/myapp/public'
    environment:
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - 'db-data:/var/lib/mysql'
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '4306:3306'

  selenium_chrome:
    image: selenium/standalone-chrome-debug
