version: '3'

volumes:
  db-data:
  public-data:
  tmp-data:

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    ports:
      - '3000:3000'
    volumes:
      - '.:/myapp'
      - 'public-data:/myapp/public'
    environment:
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - 'db-data:/var/lib/mysql'
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '4306:3306'

  selenium_chrome:
    image: selenium/standalone-chrome-debug

  nginx:
    build:
      context: nginx
      args:
        USER_NAME: $BASIC_AUTHENTICATION_USER_NAME
        PASSWORD: $BASIC_AUTHENTICATION_PASSWORD
    volumes:
      - '.:/myapp'
      - 'public-data:/myapp/public'
      - 'tmp-data:/myapp/log'
    ports:
      - '80:80'
    depends_on:
      - web
