version: 2

jobs:
  deploy:
    machine:
      python:
        version: 2.7.9

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - ${FINGERPRINT_KEY}
      - run:
          name: AWS CLIのインストール
          command: sudo pip install awscli
      - run:
          name: デプロイ
          command: ./.circleci/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy
