version: 2

jobs:
  deploy:
    machine:
      python:
        version: 2.7.9

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - ${FINGERPRINT_KEY}
      - run:
          name: ssh install
          command: yum -y install openssh-server openssh-clients
      - run:
          name: デプロイ
          command: ./.circleci/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy
